import autoFail1 from './auto-fail';
import between1 from './between';
import date1 from './date';
import double1 from './double';
import email1 from './email';
import isNotNull1 from './is-not-null';
import isTrue1 from './is-true';
import lessThan1 from './less-than';
import maxLength1 from './max-length';
import minLength1 from './min-length';
import number1 from './number';
import required1 from './required';
import zip1 from './zip';

export const autoFail = autoFail1;
export const between = between1;
export const date = date1;
export const double = double1;
export const email = email1;
export const isNotNull = isNotNull1;
export const isTrue = isTrue1;
export const lessThan = lessThan1;
export const maxLength = maxLength1;
export const minLength = minLength1;
export const number = number1;
export const required = required1;
export const zip = zip1;